spring.application.name="teledon"
spring.datasource.url=jdbc:postgresql://localhost:5432/teledon
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

rsa.public-key=classpath:/certs/public.pem
rsa.private-key=classpath:/certs/private.pem