// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main_message.proto

// Protobuf Java Version: 3.25.9
package me.alexutzzu.teledon.protos;

public final class MainMessageProtos {
  private MainMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MainMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:teledon_management.MainMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool isUpdatePayload = 1;</code>
     * @return Whether the isUpdatePayload field is set.
     */
    boolean hasIsUpdatePayload();
    /**
     * <code>optional bool isUpdatePayload = 1;</code>
     * @return The isUpdatePayload.
     */
    boolean getIsUpdatePayload();

    /**
     * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
     * @return Whether the authReq field is set.
     */
    boolean hasAuthReq();
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
     * @return The authReq.
     */
    me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest getAuthReq();
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
     */
    me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder getAuthReqOrBuilder();

    /**
     * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
     * @return Whether the authRes field is set.
     */
    boolean hasAuthRes();
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
     * @return The authRes.
     */
    me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse getAuthRes();
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
     */
    me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder getAuthResOrBuilder();

    /**
     * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
     * @return Whether the charityReq field is set.
     */
    boolean hasCharityReq();
    /**
     * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
     * @return The charityReq.
     */
    me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest getCharityReq();
    /**
     * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
     */
    me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequestOrBuilder getCharityReqOrBuilder();

    /**
     * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
     * @return Whether the charityRes field is set.
     */
    boolean hasCharityRes();
    /**
     * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
     * @return The charityRes.
     */
    me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse getCharityRes();
    /**
     * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
     */
    me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponseOrBuilder getCharityResOrBuilder();

    /**
     * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
     * @return Whether the donorReq field is set.
     */
    boolean hasDonorReq();
    /**
     * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
     * @return The donorReq.
     */
    me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest getDonorReq();
    /**
     * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
     */
    me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequestOrBuilder getDonorReqOrBuilder();

    /**
     * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
     * @return Whether the donorRes field is set.
     */
    boolean hasDonorRes();
    /**
     * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
     * @return The donorRes.
     */
    me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse getDonorRes();
    /**
     * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
     */
    me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponseOrBuilder getDonorResOrBuilder();

    /**
     * <code>.teledon_management.DonationRequest donationReq = 8;</code>
     * @return Whether the donationReq field is set.
     */
    boolean hasDonationReq();
    /**
     * <code>.teledon_management.DonationRequest donationReq = 8;</code>
     * @return The donationReq.
     */
    me.alexutzzu.teledon.protos.DonationProtos.DonationRequest getDonationReq();
    /**
     * <code>.teledon_management.DonationRequest donationReq = 8;</code>
     */
    me.alexutzzu.teledon.protos.DonationProtos.DonationRequestOrBuilder getDonationReqOrBuilder();

    /**
     * <code>.teledon_management.DonationResponse donationRes = 9;</code>
     * @return Whether the donationRes field is set.
     */
    boolean hasDonationRes();
    /**
     * <code>.teledon_management.DonationResponse donationRes = 9;</code>
     * @return The donationRes.
     */
    me.alexutzzu.teledon.protos.DonationProtos.DonationResponse getDonationRes();
    /**
     * <code>.teledon_management.DonationResponse donationRes = 9;</code>
     */
    me.alexutzzu.teledon.protos.DonationProtos.DonationResponseOrBuilder getDonationResOrBuilder();

    me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code teledon_management.MainMessage}
   */
  public static final class MainMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:teledon_management.MainMessage)
      MainMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MainMessage.newBuilder() to construct.
    private MainMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MainMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MainMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.class, me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.Builder.class);
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      AUTHREQ(2),
      AUTHRES(3),
      CHARITYREQ(4),
      CHARITYRES(5),
      DONORREQ(6),
      DONORRES(7),
      DONATIONREQ(8),
      DONATIONRES(9),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 2: return AUTHREQ;
          case 3: return AUTHRES;
          case 4: return CHARITYREQ;
          case 5: return CHARITYRES;
          case 6: return DONORREQ;
          case 7: return DONORRES;
          case 8: return DONATIONREQ;
          case 9: return DONATIONRES;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int ISUPDATEPAYLOAD_FIELD_NUMBER = 1;
    private boolean isUpdatePayload_ = false;
    /**
     * <code>optional bool isUpdatePayload = 1;</code>
     * @return Whether the isUpdatePayload field is set.
     */
    @java.lang.Override
    public boolean hasIsUpdatePayload() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool isUpdatePayload = 1;</code>
     * @return The isUpdatePayload.
     */
    @java.lang.Override
    public boolean getIsUpdatePayload() {
      return isUpdatePayload_;
    }

    public static final int AUTHREQ_FIELD_NUMBER = 2;
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
     * @return Whether the authReq field is set.
     */
    @java.lang.Override
    public boolean hasAuthReq() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
     * @return The authReq.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest getAuthReq() {
      if (payloadCase_ == 2) {
         return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder getAuthReqOrBuilder() {
      if (payloadCase_ == 2) {
         return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
    }

    public static final int AUTHRES_FIELD_NUMBER = 3;
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
     * @return Whether the authRes field is set.
     */
    @java.lang.Override
    public boolean hasAuthRes() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
     * @return The authRes.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse getAuthRes() {
      if (payloadCase_ == 3) {
         return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder getAuthResOrBuilder() {
      if (payloadCase_ == 3) {
         return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
    }

    public static final int CHARITYREQ_FIELD_NUMBER = 4;
    /**
     * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
     * @return Whether the charityReq field is set.
     */
    @java.lang.Override
    public boolean hasCharityReq() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
     * @return The charityReq.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest getCharityReq() {
      if (payloadCase_ == 4) {
         return (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequestOrBuilder getCharityReqOrBuilder() {
      if (payloadCase_ == 4) {
         return (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.getDefaultInstance();
    }

    public static final int CHARITYRES_FIELD_NUMBER = 5;
    /**
     * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
     * @return Whether the charityRes field is set.
     */
    @java.lang.Override
    public boolean hasCharityRes() {
      return payloadCase_ == 5;
    }
    /**
     * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
     * @return The charityRes.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse getCharityRes() {
      if (payloadCase_ == 5) {
         return (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponseOrBuilder getCharityResOrBuilder() {
      if (payloadCase_ == 5) {
         return (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.getDefaultInstance();
    }

    public static final int DONORREQ_FIELD_NUMBER = 6;
    /**
     * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
     * @return Whether the donorReq field is set.
     */
    @java.lang.Override
    public boolean hasDonorReq() {
      return payloadCase_ == 6;
    }
    /**
     * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
     * @return The donorReq.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest getDonorReq() {
      if (payloadCase_ == 6) {
         return (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequestOrBuilder getDonorReqOrBuilder() {
      if (payloadCase_ == 6) {
         return (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.getDefaultInstance();
    }

    public static final int DONORRES_FIELD_NUMBER = 7;
    /**
     * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
     * @return Whether the donorRes field is set.
     */
    @java.lang.Override
    public boolean hasDonorRes() {
      return payloadCase_ == 7;
    }
    /**
     * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
     * @return The donorRes.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse getDonorRes() {
      if (payloadCase_ == 7) {
         return (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponseOrBuilder getDonorResOrBuilder() {
      if (payloadCase_ == 7) {
         return (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.getDefaultInstance();
    }

    public static final int DONATIONREQ_FIELD_NUMBER = 8;
    /**
     * <code>.teledon_management.DonationRequest donationReq = 8;</code>
     * @return Whether the donationReq field is set.
     */
    @java.lang.Override
    public boolean hasDonationReq() {
      return payloadCase_ == 8;
    }
    /**
     * <code>.teledon_management.DonationRequest donationReq = 8;</code>
     * @return The donationReq.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.DonationProtos.DonationRequest getDonationReq() {
      if (payloadCase_ == 8) {
         return (me.alexutzzu.teledon.protos.DonationProtos.DonationRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.DonationRequest donationReq = 8;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.DonationProtos.DonationRequestOrBuilder getDonationReqOrBuilder() {
      if (payloadCase_ == 8) {
         return (me.alexutzzu.teledon.protos.DonationProtos.DonationRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.getDefaultInstance();
    }

    public static final int DONATIONRES_FIELD_NUMBER = 9;
    /**
     * <code>.teledon_management.DonationResponse donationRes = 9;</code>
     * @return Whether the donationRes field is set.
     */
    @java.lang.Override
    public boolean hasDonationRes() {
      return payloadCase_ == 9;
    }
    /**
     * <code>.teledon_management.DonationResponse donationRes = 9;</code>
     * @return The donationRes.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.DonationProtos.DonationResponse getDonationRes() {
      if (payloadCase_ == 9) {
         return (me.alexutzzu.teledon.protos.DonationProtos.DonationResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.DonationResponse donationRes = 9;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.DonationProtos.DonationResponseOrBuilder getDonationResOrBuilder() {
      if (payloadCase_ == 9) {
         return (me.alexutzzu.teledon.protos.DonationProtos.DonationResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, isUpdatePayload_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_);
      }
      if (payloadCase_ == 4) {
        output.writeMessage(4, (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest) payload_);
      }
      if (payloadCase_ == 5) {
        output.writeMessage(5, (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse) payload_);
      }
      if (payloadCase_ == 6) {
        output.writeMessage(6, (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest) payload_);
      }
      if (payloadCase_ == 7) {
        output.writeMessage(7, (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse) payload_);
      }
      if (payloadCase_ == 8) {
        output.writeMessage(8, (me.alexutzzu.teledon.protos.DonationProtos.DonationRequest) payload_);
      }
      if (payloadCase_ == 9) {
        output.writeMessage(9, (me.alexutzzu.teledon.protos.DonationProtos.DonationResponse) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isUpdatePayload_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_);
      }
      if (payloadCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest) payload_);
      }
      if (payloadCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse) payload_);
      }
      if (payloadCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest) payload_);
      }
      if (payloadCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse) payload_);
      }
      if (payloadCase_ == 8) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, (me.alexutzzu.teledon.protos.DonationProtos.DonationRequest) payload_);
      }
      if (payloadCase_ == 9) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, (me.alexutzzu.teledon.protos.DonationProtos.DonationResponse) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage)) {
        return super.equals(obj);
      }
      me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage other = (me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage) obj;

      if (hasIsUpdatePayload() != other.hasIsUpdatePayload()) return false;
      if (hasIsUpdatePayload()) {
        if (getIsUpdatePayload()
            != other.getIsUpdatePayload()) return false;
      }
      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 2:
          if (!getAuthReq()
              .equals(other.getAuthReq())) return false;
          break;
        case 3:
          if (!getAuthRes()
              .equals(other.getAuthRes())) return false;
          break;
        case 4:
          if (!getCharityReq()
              .equals(other.getCharityReq())) return false;
          break;
        case 5:
          if (!getCharityRes()
              .equals(other.getCharityRes())) return false;
          break;
        case 6:
          if (!getDonorReq()
              .equals(other.getDonorReq())) return false;
          break;
        case 7:
          if (!getDonorRes()
              .equals(other.getDonorRes())) return false;
          break;
        case 8:
          if (!getDonationReq()
              .equals(other.getDonationReq())) return false;
          break;
        case 9:
          if (!getDonationRes()
              .equals(other.getDonationRes())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsUpdatePayload()) {
        hash = (37 * hash) + ISUPDATEPAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsUpdatePayload());
      }
      switch (payloadCase_) {
        case 2:
          hash = (37 * hash) + AUTHREQ_FIELD_NUMBER;
          hash = (53 * hash) + getAuthReq().hashCode();
          break;
        case 3:
          hash = (37 * hash) + AUTHRES_FIELD_NUMBER;
          hash = (53 * hash) + getAuthRes().hashCode();
          break;
        case 4:
          hash = (37 * hash) + CHARITYREQ_FIELD_NUMBER;
          hash = (53 * hash) + getCharityReq().hashCode();
          break;
        case 5:
          hash = (37 * hash) + CHARITYRES_FIELD_NUMBER;
          hash = (53 * hash) + getCharityRes().hashCode();
          break;
        case 6:
          hash = (37 * hash) + DONORREQ_FIELD_NUMBER;
          hash = (53 * hash) + getDonorReq().hashCode();
          break;
        case 7:
          hash = (37 * hash) + DONORRES_FIELD_NUMBER;
          hash = (53 * hash) + getDonorRes().hashCode();
          break;
        case 8:
          hash = (37 * hash) + DONATIONREQ_FIELD_NUMBER;
          hash = (53 * hash) + getDonationReq().hashCode();
          break;
        case 9:
          hash = (37 * hash) + DONATIONRES_FIELD_NUMBER;
          hash = (53 * hash) + getDonationRes().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code teledon_management.MainMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:teledon_management.MainMessage)
        me.alexutzzu.teledon.protos.MainMessageProtos.MainMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.class, me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.Builder.class);
      }

      // Construct using me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        isUpdatePayload_ = false;
        if (authReqBuilder_ != null) {
          authReqBuilder_.clear();
        }
        if (authResBuilder_ != null) {
          authResBuilder_.clear();
        }
        if (charityReqBuilder_ != null) {
          charityReqBuilder_.clear();
        }
        if (charityResBuilder_ != null) {
          charityResBuilder_.clear();
        }
        if (donorReqBuilder_ != null) {
          donorReqBuilder_.clear();
        }
        if (donorResBuilder_ != null) {
          donorResBuilder_.clear();
        }
        if (donationReqBuilder_ != null) {
          donationReqBuilder_.clear();
        }
        if (donationResBuilder_ != null) {
          donationResBuilder_.clear();
        }
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_descriptor;
      }

      @java.lang.Override
      public me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage getDefaultInstanceForType() {
        return me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.getDefaultInstance();
      }

      @java.lang.Override
      public me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage build() {
        me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage buildPartial() {
        me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage result = new me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isUpdatePayload_ = isUpdatePayload_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      private void buildPartialOneofs(me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage result) {
        result.payloadCase_ = payloadCase_;
        result.payload_ = this.payload_;
        if (payloadCase_ == 2 &&
            authReqBuilder_ != null) {
          result.payload_ = authReqBuilder_.build();
        }
        if (payloadCase_ == 3 &&
            authResBuilder_ != null) {
          result.payload_ = authResBuilder_.build();
        }
        if (payloadCase_ == 4 &&
            charityReqBuilder_ != null) {
          result.payload_ = charityReqBuilder_.build();
        }
        if (payloadCase_ == 5 &&
            charityResBuilder_ != null) {
          result.payload_ = charityResBuilder_.build();
        }
        if (payloadCase_ == 6 &&
            donorReqBuilder_ != null) {
          result.payload_ = donorReqBuilder_.build();
        }
        if (payloadCase_ == 7 &&
            donorResBuilder_ != null) {
          result.payload_ = donorResBuilder_.build();
        }
        if (payloadCase_ == 8 &&
            donationReqBuilder_ != null) {
          result.payload_ = donationReqBuilder_.build();
        }
        if (payloadCase_ == 9 &&
            donationResBuilder_ != null) {
          result.payload_ = donationResBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage) {
          return mergeFrom((me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage other) {
        if (other == me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.getDefaultInstance()) return this;
        if (other.hasIsUpdatePayload()) {
          setIsUpdatePayload(other.getIsUpdatePayload());
        }
        switch (other.getPayloadCase()) {
          case AUTHREQ: {
            mergeAuthReq(other.getAuthReq());
            break;
          }
          case AUTHRES: {
            mergeAuthRes(other.getAuthRes());
            break;
          }
          case CHARITYREQ: {
            mergeCharityReq(other.getCharityReq());
            break;
          }
          case CHARITYRES: {
            mergeCharityRes(other.getCharityRes());
            break;
          }
          case DONORREQ: {
            mergeDonorReq(other.getDonorReq());
            break;
          }
          case DONORRES: {
            mergeDonorRes(other.getDonorRes());
            break;
          }
          case DONATIONREQ: {
            mergeDonationReq(other.getDonationReq());
            break;
          }
          case DONATIONRES: {
            mergeDonationRes(other.getDonationRes());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                isUpdatePayload_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getAuthReqFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getAuthResFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 3;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getCharityReqFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 4;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getCharityResFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 5;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getDonorReqFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 6;
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getDonorResFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 7;
                break;
              } // case 58
              case 66: {
                input.readMessage(
                    getDonationReqFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 8;
                break;
              } // case 66
              case 74: {
                input.readMessage(
                    getDonationResFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 9;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private boolean isUpdatePayload_ ;
      /**
       * <code>optional bool isUpdatePayload = 1;</code>
       * @return Whether the isUpdatePayload field is set.
       */
      @java.lang.Override
      public boolean hasIsUpdatePayload() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool isUpdatePayload = 1;</code>
       * @return The isUpdatePayload.
       */
      @java.lang.Override
      public boolean getIsUpdatePayload() {
        return isUpdatePayload_;
      }
      /**
       * <code>optional bool isUpdatePayload = 1;</code>
       * @param value The isUpdatePayload to set.
       * @return This builder for chaining.
       */
      public Builder setIsUpdatePayload(boolean value) {

        isUpdatePayload_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isUpdatePayload = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsUpdatePayload() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isUpdatePayload_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder> authReqBuilder_;
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
       * @return Whether the authReq field is set.
       */
      @java.lang.Override
      public boolean hasAuthReq() {
        return payloadCase_ == 2;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
       * @return The authReq.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest getAuthReq() {
        if (authReqBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return authReqBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
       */
      public Builder setAuthReq(me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest value) {
        if (authReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          authReqBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
       */
      public Builder setAuthReq(
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder builderForValue) {
        if (authReqBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          authReqBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
       */
      public Builder mergeAuthReq(me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest value) {
        if (authReqBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.newBuilder((me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            authReqBuilder_.mergeFrom(value);
          } else {
            authReqBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
       */
      public Builder clearAuthReq() {
        if (authReqBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          authReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
       */
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder getAuthReqBuilder() {
        return getAuthReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder getAuthReqOrBuilder() {
        if ((payloadCase_ == 2) && (authReqBuilder_ != null)) {
          return authReqBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder> 
          getAuthReqFieldBuilder() {
        if (authReqBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
          }
          authReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder>(
                  (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();
        return authReqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder> authResBuilder_;
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
       * @return Whether the authRes field is set.
       */
      @java.lang.Override
      public boolean hasAuthRes() {
        return payloadCase_ == 3;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
       * @return The authRes.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse getAuthRes() {
        if (authResBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return authResBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
       */
      public Builder setAuthRes(me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse value) {
        if (authResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          authResBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
       */
      public Builder setAuthRes(
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder builderForValue) {
        if (authResBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          authResBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
       */
      public Builder mergeAuthRes(me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse value) {
        if (authResBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.newBuilder((me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            authResBuilder_.mergeFrom(value);
          } else {
            authResBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
       */
      public Builder clearAuthRes() {
        if (authResBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          authResBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
       */
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder getAuthResBuilder() {
        return getAuthResFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder getAuthResOrBuilder() {
        if ((payloadCase_ == 3) && (authResBuilder_ != null)) {
          return authResBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder> 
          getAuthResFieldBuilder() {
        if (authResBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
          }
          authResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder>(
                  (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        onChanged();
        return authResBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.Builder, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequestOrBuilder> charityReqBuilder_;
      /**
       * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
       * @return Whether the charityReq field is set.
       */
      @java.lang.Override
      public boolean hasCharityReq() {
        return payloadCase_ == 4;
      }
      /**
       * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
       * @return The charityReq.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest getCharityReq() {
        if (charityReqBuilder_ == null) {
          if (payloadCase_ == 4) {
            return (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.getDefaultInstance();
        } else {
          if (payloadCase_ == 4) {
            return charityReqBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
       */
      public Builder setCharityReq(me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest value) {
        if (charityReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          charityReqBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
       */
      public Builder setCharityReq(
          me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.Builder builderForValue) {
        if (charityReqBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          charityReqBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
       */
      public Builder mergeCharityReq(me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest value) {
        if (charityReqBuilder_ == null) {
          if (payloadCase_ == 4 &&
              payload_ != me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.newBuilder((me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 4) {
            charityReqBuilder_.mergeFrom(value);
          } else {
            charityReqBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
       */
      public Builder clearCharityReq() {
        if (charityReqBuilder_ == null) {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
          }
          charityReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
       */
      public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.Builder getCharityReqBuilder() {
        return getCharityReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequestOrBuilder getCharityReqOrBuilder() {
        if ((payloadCase_ == 4) && (charityReqBuilder_ != null)) {
          return charityReqBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 4) {
            return (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.CharityDtoRequest charityReq = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.Builder, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequestOrBuilder> 
          getCharityReqFieldBuilder() {
        if (charityReqBuilder_ == null) {
          if (!(payloadCase_ == 4)) {
            payload_ = me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.getDefaultInstance();
          }
          charityReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest.Builder, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequestOrBuilder>(
                  (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoRequest) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 4;
        onChanged();
        return charityReqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.Builder, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponseOrBuilder> charityResBuilder_;
      /**
       * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
       * @return Whether the charityRes field is set.
       */
      @java.lang.Override
      public boolean hasCharityRes() {
        return payloadCase_ == 5;
      }
      /**
       * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
       * @return The charityRes.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse getCharityRes() {
        if (charityResBuilder_ == null) {
          if (payloadCase_ == 5) {
            return (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.getDefaultInstance();
        } else {
          if (payloadCase_ == 5) {
            return charityResBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
       */
      public Builder setCharityRes(me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse value) {
        if (charityResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          charityResBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
       */
      public Builder setCharityRes(
          me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.Builder builderForValue) {
        if (charityResBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          charityResBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
       */
      public Builder mergeCharityRes(me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse value) {
        if (charityResBuilder_ == null) {
          if (payloadCase_ == 5 &&
              payload_ != me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.newBuilder((me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 5) {
            charityResBuilder_.mergeFrom(value);
          } else {
            charityResBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
       */
      public Builder clearCharityRes() {
        if (charityResBuilder_ == null) {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
          }
          charityResBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
       */
      public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.Builder getCharityResBuilder() {
        return getCharityResFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponseOrBuilder getCharityResOrBuilder() {
        if ((payloadCase_ == 5) && (charityResBuilder_ != null)) {
          return charityResBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 5) {
            return (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.CharityDtoResponse charityRes = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.Builder, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponseOrBuilder> 
          getCharityResFieldBuilder() {
        if (charityResBuilder_ == null) {
          if (!(payloadCase_ == 5)) {
            payload_ = me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.getDefaultInstance();
          }
          charityResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse.Builder, me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponseOrBuilder>(
                  (me.alexutzzu.teledon.protos.CharityProtos.CharityDtoResponse) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 5;
        onChanged();
        return charityResBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.Builder, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequestOrBuilder> donorReqBuilder_;
      /**
       * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
       * @return Whether the donorReq field is set.
       */
      @java.lang.Override
      public boolean hasDonorReq() {
        return payloadCase_ == 6;
      }
      /**
       * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
       * @return The donorReq.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest getDonorReq() {
        if (donorReqBuilder_ == null) {
          if (payloadCase_ == 6) {
            return (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.getDefaultInstance();
        } else {
          if (payloadCase_ == 6) {
            return donorReqBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
       */
      public Builder setDonorReq(me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest value) {
        if (donorReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          donorReqBuilder_.setMessage(value);
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
       */
      public Builder setDonorReq(
          me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.Builder builderForValue) {
        if (donorReqBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          donorReqBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
       */
      public Builder mergeDonorReq(me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest value) {
        if (donorReqBuilder_ == null) {
          if (payloadCase_ == 6 &&
              payload_ != me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.newBuilder((me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 6) {
            donorReqBuilder_.mergeFrom(value);
          } else {
            donorReqBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
       */
      public Builder clearDonorReq() {
        if (donorReqBuilder_ == null) {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
          }
          donorReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
       */
      public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.Builder getDonorReqBuilder() {
        return getDonorReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequestOrBuilder getDonorReqOrBuilder() {
        if ((payloadCase_ == 6) && (donorReqBuilder_ != null)) {
          return donorReqBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 6) {
            return (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.DonorDtoRequest donorReq = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.Builder, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequestOrBuilder> 
          getDonorReqFieldBuilder() {
        if (donorReqBuilder_ == null) {
          if (!(payloadCase_ == 6)) {
            payload_ = me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.getDefaultInstance();
          }
          donorReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest.Builder, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequestOrBuilder>(
                  (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoRequest) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 6;
        onChanged();
        return donorReqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.Builder, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponseOrBuilder> donorResBuilder_;
      /**
       * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
       * @return Whether the donorRes field is set.
       */
      @java.lang.Override
      public boolean hasDonorRes() {
        return payloadCase_ == 7;
      }
      /**
       * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
       * @return The donorRes.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse getDonorRes() {
        if (donorResBuilder_ == null) {
          if (payloadCase_ == 7) {
            return (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.getDefaultInstance();
        } else {
          if (payloadCase_ == 7) {
            return donorResBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
       */
      public Builder setDonorRes(me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse value) {
        if (donorResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          donorResBuilder_.setMessage(value);
        }
        payloadCase_ = 7;
        return this;
      }
      /**
       * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
       */
      public Builder setDonorRes(
          me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.Builder builderForValue) {
        if (donorResBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          donorResBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 7;
        return this;
      }
      /**
       * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
       */
      public Builder mergeDonorRes(me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse value) {
        if (donorResBuilder_ == null) {
          if (payloadCase_ == 7 &&
              payload_ != me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.newBuilder((me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 7) {
            donorResBuilder_.mergeFrom(value);
          } else {
            donorResBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 7;
        return this;
      }
      /**
       * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
       */
      public Builder clearDonorRes() {
        if (donorResBuilder_ == null) {
          if (payloadCase_ == 7) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 7) {
            payloadCase_ = 0;
            payload_ = null;
          }
          donorResBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
       */
      public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.Builder getDonorResBuilder() {
        return getDonorResFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponseOrBuilder getDonorResOrBuilder() {
        if ((payloadCase_ == 7) && (donorResBuilder_ != null)) {
          return donorResBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 7) {
            return (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.DonorDtoResponse donorRes = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.Builder, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponseOrBuilder> 
          getDonorResFieldBuilder() {
        if (donorResBuilder_ == null) {
          if (!(payloadCase_ == 7)) {
            payload_ = me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.getDefaultInstance();
          }
          donorResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse.Builder, me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponseOrBuilder>(
                  (me.alexutzzu.teledon.protos.DonorProtos.DonorDtoResponse) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 7;
        onChanged();
        return donorResBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.DonationProtos.DonationRequest, me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.Builder, me.alexutzzu.teledon.protos.DonationProtos.DonationRequestOrBuilder> donationReqBuilder_;
      /**
       * <code>.teledon_management.DonationRequest donationReq = 8;</code>
       * @return Whether the donationReq field is set.
       */
      @java.lang.Override
      public boolean hasDonationReq() {
        return payloadCase_ == 8;
      }
      /**
       * <code>.teledon_management.DonationRequest donationReq = 8;</code>
       * @return The donationReq.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.DonationProtos.DonationRequest getDonationReq() {
        if (donationReqBuilder_ == null) {
          if (payloadCase_ == 8) {
            return (me.alexutzzu.teledon.protos.DonationProtos.DonationRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.getDefaultInstance();
        } else {
          if (payloadCase_ == 8) {
            return donationReqBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.DonationRequest donationReq = 8;</code>
       */
      public Builder setDonationReq(me.alexutzzu.teledon.protos.DonationProtos.DonationRequest value) {
        if (donationReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          donationReqBuilder_.setMessage(value);
        }
        payloadCase_ = 8;
        return this;
      }
      /**
       * <code>.teledon_management.DonationRequest donationReq = 8;</code>
       */
      public Builder setDonationReq(
          me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.Builder builderForValue) {
        if (donationReqBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          donationReqBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 8;
        return this;
      }
      /**
       * <code>.teledon_management.DonationRequest donationReq = 8;</code>
       */
      public Builder mergeDonationReq(me.alexutzzu.teledon.protos.DonationProtos.DonationRequest value) {
        if (donationReqBuilder_ == null) {
          if (payloadCase_ == 8 &&
              payload_ != me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.newBuilder((me.alexutzzu.teledon.protos.DonationProtos.DonationRequest) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 8) {
            donationReqBuilder_.mergeFrom(value);
          } else {
            donationReqBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 8;
        return this;
      }
      /**
       * <code>.teledon_management.DonationRequest donationReq = 8;</code>
       */
      public Builder clearDonationReq() {
        if (donationReqBuilder_ == null) {
          if (payloadCase_ == 8) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 8) {
            payloadCase_ = 0;
            payload_ = null;
          }
          donationReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.DonationRequest donationReq = 8;</code>
       */
      public me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.Builder getDonationReqBuilder() {
        return getDonationReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.DonationRequest donationReq = 8;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.DonationProtos.DonationRequestOrBuilder getDonationReqOrBuilder() {
        if ((payloadCase_ == 8) && (donationReqBuilder_ != null)) {
          return donationReqBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 8) {
            return (me.alexutzzu.teledon.protos.DonationProtos.DonationRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.DonationRequest donationReq = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.DonationProtos.DonationRequest, me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.Builder, me.alexutzzu.teledon.protos.DonationProtos.DonationRequestOrBuilder> 
          getDonationReqFieldBuilder() {
        if (donationReqBuilder_ == null) {
          if (!(payloadCase_ == 8)) {
            payload_ = me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.getDefaultInstance();
          }
          donationReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.DonationProtos.DonationRequest, me.alexutzzu.teledon.protos.DonationProtos.DonationRequest.Builder, me.alexutzzu.teledon.protos.DonationProtos.DonationRequestOrBuilder>(
                  (me.alexutzzu.teledon.protos.DonationProtos.DonationRequest) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 8;
        onChanged();
        return donationReqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.DonationProtos.DonationResponse, me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.Builder, me.alexutzzu.teledon.protos.DonationProtos.DonationResponseOrBuilder> donationResBuilder_;
      /**
       * <code>.teledon_management.DonationResponse donationRes = 9;</code>
       * @return Whether the donationRes field is set.
       */
      @java.lang.Override
      public boolean hasDonationRes() {
        return payloadCase_ == 9;
      }
      /**
       * <code>.teledon_management.DonationResponse donationRes = 9;</code>
       * @return The donationRes.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.DonationProtos.DonationResponse getDonationRes() {
        if (donationResBuilder_ == null) {
          if (payloadCase_ == 9) {
            return (me.alexutzzu.teledon.protos.DonationProtos.DonationResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.getDefaultInstance();
        } else {
          if (payloadCase_ == 9) {
            return donationResBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.DonationResponse donationRes = 9;</code>
       */
      public Builder setDonationRes(me.alexutzzu.teledon.protos.DonationProtos.DonationResponse value) {
        if (donationResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          donationResBuilder_.setMessage(value);
        }
        payloadCase_ = 9;
        return this;
      }
      /**
       * <code>.teledon_management.DonationResponse donationRes = 9;</code>
       */
      public Builder setDonationRes(
          me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.Builder builderForValue) {
        if (donationResBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          donationResBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 9;
        return this;
      }
      /**
       * <code>.teledon_management.DonationResponse donationRes = 9;</code>
       */
      public Builder mergeDonationRes(me.alexutzzu.teledon.protos.DonationProtos.DonationResponse value) {
        if (donationResBuilder_ == null) {
          if (payloadCase_ == 9 &&
              payload_ != me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.newBuilder((me.alexutzzu.teledon.protos.DonationProtos.DonationResponse) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 9) {
            donationResBuilder_.mergeFrom(value);
          } else {
            donationResBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 9;
        return this;
      }
      /**
       * <code>.teledon_management.DonationResponse donationRes = 9;</code>
       */
      public Builder clearDonationRes() {
        if (donationResBuilder_ == null) {
          if (payloadCase_ == 9) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 9) {
            payloadCase_ = 0;
            payload_ = null;
          }
          donationResBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.DonationResponse donationRes = 9;</code>
       */
      public me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.Builder getDonationResBuilder() {
        return getDonationResFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.DonationResponse donationRes = 9;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.DonationProtos.DonationResponseOrBuilder getDonationResOrBuilder() {
        if ((payloadCase_ == 9) && (donationResBuilder_ != null)) {
          return donationResBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 9) {
            return (me.alexutzzu.teledon.protos.DonationProtos.DonationResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.DonationResponse donationRes = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.DonationProtos.DonationResponse, me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.Builder, me.alexutzzu.teledon.protos.DonationProtos.DonationResponseOrBuilder> 
          getDonationResFieldBuilder() {
        if (donationResBuilder_ == null) {
          if (!(payloadCase_ == 9)) {
            payload_ = me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.getDefaultInstance();
          }
          donationResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.DonationProtos.DonationResponse, me.alexutzzu.teledon.protos.DonationProtos.DonationResponse.Builder, me.alexutzzu.teledon.protos.DonationProtos.DonationResponseOrBuilder>(
                  (me.alexutzzu.teledon.protos.DonationProtos.DonationResponse) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 9;
        onChanged();
        return donationResBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:teledon_management.MainMessage)
    }

    // @@protoc_insertion_point(class_scope:teledon_management.MainMessage)
    private static final me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage();
    }

    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MainMessage>
        PARSER = new com.google.protobuf.AbstractParser<MainMessage>() {
      @java.lang.Override
      public MainMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MainMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MainMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teledon_management_MainMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teledon_management_MainMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022main_message.proto\022\022teledon_management" +
      "\032\rcharity.proto\032\017auth_user.proto\032\013donor." +
      "proto\032\016donation.proto\"\242\004\n\013MainMessage\022\034\n" +
      "\017isUpdatePayload\030\001 \001(\010H\001\210\001\001\0226\n\007authReq\030\002" +
      " \001(\0132#.teledon_management.AuthUserReques" +
      "tH\000\0227\n\007authRes\030\003 \001(\0132$.teledon_managemen" +
      "t.AuthUserResponseH\000\022;\n\ncharityReq\030\004 \001(\013" +
      "2%.teledon_management.CharityDtoRequestH" +
      "\000\022<\n\ncharityRes\030\005 \001(\0132&.teledon_manageme" +
      "nt.CharityDtoResponseH\000\0227\n\010donorReq\030\006 \001(" +
      "\0132#.teledon_management.DonorDtoRequestH\000" +
      "\0228\n\010donorRes\030\007 \001(\0132$.teledon_management." +
      "DonorDtoResponseH\000\022:\n\013donationReq\030\010 \001(\0132" +
      "#.teledon_management.DonationRequestH\000\022;" +
      "\n\013donationRes\030\t \001(\0132$.teledon_management" +
      ".DonationResponseH\000B\t\n\007payloadB\022\n\020_isUpd" +
      "atePayloadBQ\n\033me.alexutzzu.teledon.proto" +
      "sB\021MainMessageProtosP\000\252\002\034teledon_managem" +
      "ent_ui.Protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.alexutzzu.teledon.protos.CharityProtos.getDescriptor(),
          me.alexutzzu.teledon.protos.AuthUserProtos.getDescriptor(),
          me.alexutzzu.teledon.protos.DonorProtos.getDescriptor(),
          me.alexutzzu.teledon.protos.DonationProtos.getDescriptor(),
        });
    internal_static_teledon_management_MainMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_teledon_management_MainMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teledon_management_MainMessage_descriptor,
        new java.lang.String[] { "IsUpdatePayload", "AuthReq", "AuthRes", "CharityReq", "CharityRes", "DonorReq", "DonorRes", "DonationReq", "DonationRes", "Payload", });
    me.alexutzzu.teledon.protos.CharityProtos.getDescriptor();
    me.alexutzzu.teledon.protos.AuthUserProtos.getDescriptor();
    me.alexutzzu.teledon.protos.DonorProtos.getDescriptor();
    me.alexutzzu.teledon.protos.DonationProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
