// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main_message.proto

// Protobuf Java Version: 3.25.9
package me.alexutzzu.teledon.protos;

public final class MainMessageProtos {
  private MainMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MainMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:teledon_management.MainMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
     * @return Whether the authReq field is set.
     */
    boolean hasAuthReq();
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
     * @return The authReq.
     */
    me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest getAuthReq();
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
     */
    me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder getAuthReqOrBuilder();

    /**
     * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
     * @return Whether the authRes field is set.
     */
    boolean hasAuthRes();
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
     * @return The authRes.
     */
    me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse getAuthRes();
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
     */
    me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder getAuthResOrBuilder();

    me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code teledon_management.MainMessage}
   */
  public static final class MainMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:teledon_management.MainMessage)
      MainMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MainMessage.newBuilder() to construct.
    private MainMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MainMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MainMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.class, me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.Builder.class);
    }

    private int payloadCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      AUTHREQ(1),
      AUTHRES(2),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 1: return AUTHREQ;
          case 2: return AUTHRES;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int AUTHREQ_FIELD_NUMBER = 1;
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
     * @return Whether the authReq field is set.
     */
    @java.lang.Override
    public boolean hasAuthReq() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
     * @return The authReq.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest getAuthReq() {
      if (payloadCase_ == 1) {
         return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder getAuthReqOrBuilder() {
      if (payloadCase_ == 1) {
         return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_;
      }
      return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
    }

    public static final int AUTHRES_FIELD_NUMBER = 2;
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
     * @return Whether the authRes field is set.
     */
    @java.lang.Override
    public boolean hasAuthRes() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
     * @return The authRes.
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse getAuthRes() {
      if (payloadCase_ == 2) {
         return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
    }
    /**
     * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
     */
    @java.lang.Override
    public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder getAuthResOrBuilder() {
      if (payloadCase_ == 2) {
         return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_;
      }
      return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payloadCase_ == 1) {
        output.writeMessage(1, (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payloadCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage)) {
        return super.equals(obj);
      }
      me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage other = (me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage) obj;

      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 1:
          if (!getAuthReq()
              .equals(other.getAuthReq())) return false;
          break;
        case 2:
          if (!getAuthRes()
              .equals(other.getAuthRes())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (payloadCase_) {
        case 1:
          hash = (37 * hash) + AUTHREQ_FIELD_NUMBER;
          hash = (53 * hash) + getAuthReq().hashCode();
          break;
        case 2:
          hash = (37 * hash) + AUTHRES_FIELD_NUMBER;
          hash = (53 * hash) + getAuthRes().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code teledon_management.MainMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:teledon_management.MainMessage)
        me.alexutzzu.teledon.protos.MainMessageProtos.MainMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.class, me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.Builder.class);
      }

      // Construct using me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (authReqBuilder_ != null) {
          authReqBuilder_.clear();
        }
        if (authResBuilder_ != null) {
          authResBuilder_.clear();
        }
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.alexutzzu.teledon.protos.MainMessageProtos.internal_static_teledon_management_MainMessage_descriptor;
      }

      @java.lang.Override
      public me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage getDefaultInstanceForType() {
        return me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.getDefaultInstance();
      }

      @java.lang.Override
      public me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage build() {
        me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage buildPartial() {
        me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage result = new me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage result) {
        result.payloadCase_ = payloadCase_;
        result.payload_ = this.payload_;
        if (payloadCase_ == 1 &&
            authReqBuilder_ != null) {
          result.payload_ = authReqBuilder_.build();
        }
        if (payloadCase_ == 2 &&
            authResBuilder_ != null) {
          result.payload_ = authResBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage) {
          return mergeFrom((me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage other) {
        if (other == me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage.getDefaultInstance()) return this;
        switch (other.getPayloadCase()) {
          case AUTHREQ: {
            mergeAuthReq(other.getAuthReq());
            break;
          }
          case AUTHRES: {
            mergeAuthRes(other.getAuthRes());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAuthReqFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 1;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getAuthResFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 2;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder> authReqBuilder_;
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
       * @return Whether the authReq field is set.
       */
      @java.lang.Override
      public boolean hasAuthReq() {
        return payloadCase_ == 1;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
       * @return The authReq.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest getAuthReq() {
        if (authReqBuilder_ == null) {
          if (payloadCase_ == 1) {
            return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
        } else {
          if (payloadCase_ == 1) {
            return authReqBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
       */
      public Builder setAuthReq(me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest value) {
        if (authReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          authReqBuilder_.setMessage(value);
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
       */
      public Builder setAuthReq(
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder builderForValue) {
        if (authReqBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          authReqBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
       */
      public Builder mergeAuthReq(me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest value) {
        if (authReqBuilder_ == null) {
          if (payloadCase_ == 1 &&
              payload_ != me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.newBuilder((me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 1) {
            authReqBuilder_.mergeFrom(value);
          } else {
            authReqBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
       */
      public Builder clearAuthReq() {
        if (authReqBuilder_ == null) {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
          }
          authReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
       */
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder getAuthReqBuilder() {
        return getAuthReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder getAuthReqOrBuilder() {
        if ((payloadCase_ == 1) && (authReqBuilder_ != null)) {
          return authReqBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 1) {
            return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_;
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.AuthUserRequest authReq = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder> 
          getAuthReqFieldBuilder() {
        if (authReqBuilder_ == null) {
          if (!(payloadCase_ == 1)) {
            payload_ = me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.getDefaultInstance();
          }
          authReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequestOrBuilder>(
                  (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserRequest) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 1;
        onChanged();
        return authReqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder> authResBuilder_;
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
       * @return Whether the authRes field is set.
       */
      @java.lang.Override
      public boolean hasAuthRes() {
        return payloadCase_ == 2;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
       * @return The authRes.
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse getAuthRes() {
        if (authResBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return authResBuilder_.getMessage();
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
       */
      public Builder setAuthRes(me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse value) {
        if (authResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          authResBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
       */
      public Builder setAuthRes(
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder builderForValue) {
        if (authResBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          authResBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
       */
      public Builder mergeAuthRes(me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse value) {
        if (authResBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance()) {
            payload_ = me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.newBuilder((me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            authResBuilder_.mergeFrom(value);
          } else {
            authResBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
       */
      public Builder clearAuthRes() {
        if (authResBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          authResBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
       */
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder getAuthResBuilder() {
        return getAuthResFieldBuilder().getBuilder();
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
       */
      @java.lang.Override
      public me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder getAuthResOrBuilder() {
        if ((payloadCase_ == 2) && (authResBuilder_ != null)) {
          return authResBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_;
          }
          return me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.teledon_management.AuthUserResponse authRes = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder> 
          getAuthResFieldBuilder() {
        if (authResBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.getDefaultInstance();
          }
          authResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse.Builder, me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponseOrBuilder>(
                  (me.alexutzzu.teledon.protos.AuthUserProtos.AuthUserResponse) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();
        return authResBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:teledon_management.MainMessage)
    }

    // @@protoc_insertion_point(class_scope:teledon_management.MainMessage)
    private static final me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage();
    }

    public static me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MainMessage>
        PARSER = new com.google.protobuf.AbstractParser<MainMessage>() {
      @java.lang.Override
      public MainMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MainMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MainMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.alexutzzu.teledon.protos.MainMessageProtos.MainMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teledon_management_MainMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teledon_management_MainMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022main_message.proto\022\022teledon_management" +
      "\032\017auth_user.proto\"\211\001\n\013MainMessage\0226\n\007aut" +
      "hReq\030\001 \001(\0132#.teledon_management.AuthUser" +
      "RequestH\000\0227\n\007authRes\030\002 \001(\0132$.teledon_man" +
      "agement.AuthUserResponseH\000B\t\n\007payloadB2\n" +
      "\033me.alexutzzu.teledon.protosB\021MainMessag" +
      "eProtosP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.alexutzzu.teledon.protos.AuthUserProtos.getDescriptor(),
        });
    internal_static_teledon_management_MainMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_teledon_management_MainMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teledon_management_MainMessage_descriptor,
        new java.lang.String[] { "AuthReq", "AuthRes", "Payload", });
    me.alexutzzu.teledon.protos.AuthUserProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
