// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: main_message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace teledon_management_ui.Protos {

  /// <summary>Holder for reflection information generated from main_message.proto</summary>
  public static partial class MainMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for main_message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MainMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJtYWluX21lc3NhZ2UucHJvdG8SEnRlbGVkb25fbWFuYWdlbWVudBoNY2hh",
            "cml0eS5wcm90bxoPYXV0aF91c2VyLnByb3RvIrYCCgtNYWluTWVzc2FnZRI2",
            "CgdhdXRoUmVxGAEgASgLMiMudGVsZWRvbl9tYW5hZ2VtZW50LkF1dGhVc2Vy",
            "UmVxdWVzdEgAEjcKB2F1dGhSZXMYAiABKAsyJC50ZWxlZG9uX21hbmFnZW1l",
            "bnQuQXV0aFVzZXJSZXNwb25zZUgAEjsKCmNoYXJpdHlSZXEYAyABKAsyJS50",
            "ZWxlZG9uX21hbmFnZW1lbnQuQ2hhcml0eUR0b1JlcXVlc3RIABI8CgpjaGFy",
            "aXR5UmVzGAQgASgLMiYudGVsZWRvbl9tYW5hZ2VtZW50LkNoYXJpdHlEdG9S",
            "ZXNwb25zZUgAEhwKD2lzVXBkYXRlUGF5bG9hZBgFIAEoCEgBiAEBQgkKB3Bh",
            "eWxvYWRCEgoQX2lzVXBkYXRlUGF5bG9hZEJRChttZS5hbGV4dXR6enUudGVs",
            "ZWRvbi5wcm90b3NCEU1haW5NZXNzYWdlUHJvdG9zUACqAhx0ZWxlZG9uX21h",
            "bmFnZW1lbnRfdWkuUHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::teledon_management_ui.Protos.CharityReflection.Descriptor, global::teledon_management_ui.Protos.AuthUserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::teledon_management_ui.Protos.MainMessage), global::teledon_management_ui.Protos.MainMessage.Parser, new[]{ "AuthReq", "AuthRes", "CharityReq", "CharityRes", "IsUpdatePayload" }, new[]{ "Payload", "IsUpdatePayload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MainMessage : pb::IMessage<MainMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MainMessage> _parser = new pb::MessageParser<MainMessage>(() => new MainMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MainMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::teledon_management_ui.Protos.MainMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainMessage(MainMessage other) : this() {
      _hasBits0 = other._hasBits0;
      isUpdatePayload_ = other.isUpdatePayload_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.AuthReq:
          AuthReq = other.AuthReq.Clone();
          break;
        case PayloadOneofCase.AuthRes:
          AuthRes = other.AuthRes.Clone();
          break;
        case PayloadOneofCase.CharityReq:
          CharityReq = other.CharityReq.Clone();
          break;
        case PayloadOneofCase.CharityRes:
          CharityRes = other.CharityRes.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainMessage Clone() {
      return new MainMessage(this);
    }

    /// <summary>Field number for the "authReq" field.</summary>
    public const int AuthReqFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.AuthUserRequest AuthReq {
      get { return payloadCase_ == PayloadOneofCase.AuthReq ? (global::teledon_management_ui.Protos.AuthUserRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.AuthReq;
      }
    }

    /// <summary>Field number for the "authRes" field.</summary>
    public const int AuthResFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.AuthUserResponse AuthRes {
      get { return payloadCase_ == PayloadOneofCase.AuthRes ? (global::teledon_management_ui.Protos.AuthUserResponse) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.AuthRes;
      }
    }

    /// <summary>Field number for the "charityReq" field.</summary>
    public const int CharityReqFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.CharityDtoRequest CharityReq {
      get { return payloadCase_ == PayloadOneofCase.CharityReq ? (global::teledon_management_ui.Protos.CharityDtoRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CharityReq;
      }
    }

    /// <summary>Field number for the "charityRes" field.</summary>
    public const int CharityResFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.CharityDtoResponse CharityRes {
      get { return payloadCase_ == PayloadOneofCase.CharityRes ? (global::teledon_management_ui.Protos.CharityDtoResponse) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CharityRes;
      }
    }

    /// <summary>Field number for the "isUpdatePayload" field.</summary>
    public const int IsUpdatePayloadFieldNumber = 5;
    private readonly static bool IsUpdatePayloadDefaultValue = false;

    private bool isUpdatePayload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsUpdatePayload {
      get { if ((_hasBits0 & 1) != 0) { return isUpdatePayload_; } else { return IsUpdatePayloadDefaultValue; } }
      set {
        _hasBits0 |= 1;
        isUpdatePayload_ = value;
      }
    }
    /// <summary>Gets whether the "isUpdatePayload" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIsUpdatePayload {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "isUpdatePayload" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIsUpdatePayload() {
      _hasBits0 &= ~1;
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      AuthReq = 1,
      AuthRes = 2,
      CharityReq = 3,
      CharityRes = 4,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MainMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MainMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AuthReq, other.AuthReq)) return false;
      if (!object.Equals(AuthRes, other.AuthRes)) return false;
      if (!object.Equals(CharityReq, other.CharityReq)) return false;
      if (!object.Equals(CharityRes, other.CharityRes)) return false;
      if (IsUpdatePayload != other.IsUpdatePayload) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.AuthReq) hash ^= AuthReq.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.AuthRes) hash ^= AuthRes.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CharityReq) hash ^= CharityReq.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CharityRes) hash ^= CharityRes.GetHashCode();
      if (HasIsUpdatePayload) hash ^= IsUpdatePayload.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payloadCase_ == PayloadOneofCase.AuthReq) {
        output.WriteRawTag(10);
        output.WriteMessage(AuthReq);
      }
      if (payloadCase_ == PayloadOneofCase.AuthRes) {
        output.WriteRawTag(18);
        output.WriteMessage(AuthRes);
      }
      if (payloadCase_ == PayloadOneofCase.CharityReq) {
        output.WriteRawTag(26);
        output.WriteMessage(CharityReq);
      }
      if (payloadCase_ == PayloadOneofCase.CharityRes) {
        output.WriteRawTag(34);
        output.WriteMessage(CharityRes);
      }
      if (HasIsUpdatePayload) {
        output.WriteRawTag(40);
        output.WriteBool(IsUpdatePayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payloadCase_ == PayloadOneofCase.AuthReq) {
        output.WriteRawTag(10);
        output.WriteMessage(AuthReq);
      }
      if (payloadCase_ == PayloadOneofCase.AuthRes) {
        output.WriteRawTag(18);
        output.WriteMessage(AuthRes);
      }
      if (payloadCase_ == PayloadOneofCase.CharityReq) {
        output.WriteRawTag(26);
        output.WriteMessage(CharityReq);
      }
      if (payloadCase_ == PayloadOneofCase.CharityRes) {
        output.WriteRawTag(34);
        output.WriteMessage(CharityRes);
      }
      if (HasIsUpdatePayload) {
        output.WriteRawTag(40);
        output.WriteBool(IsUpdatePayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.AuthReq) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AuthReq);
      }
      if (payloadCase_ == PayloadOneofCase.AuthRes) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AuthRes);
      }
      if (payloadCase_ == PayloadOneofCase.CharityReq) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CharityReq);
      }
      if (payloadCase_ == PayloadOneofCase.CharityRes) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CharityRes);
      }
      if (HasIsUpdatePayload) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MainMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasIsUpdatePayload) {
        IsUpdatePayload = other.IsUpdatePayload;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.AuthReq:
          if (AuthReq == null) {
            AuthReq = new global::teledon_management_ui.Protos.AuthUserRequest();
          }
          AuthReq.MergeFrom(other.AuthReq);
          break;
        case PayloadOneofCase.AuthRes:
          if (AuthRes == null) {
            AuthRes = new global::teledon_management_ui.Protos.AuthUserResponse();
          }
          AuthRes.MergeFrom(other.AuthRes);
          break;
        case PayloadOneofCase.CharityReq:
          if (CharityReq == null) {
            CharityReq = new global::teledon_management_ui.Protos.CharityDtoRequest();
          }
          CharityReq.MergeFrom(other.CharityReq);
          break;
        case PayloadOneofCase.CharityRes:
          if (CharityRes == null) {
            CharityRes = new global::teledon_management_ui.Protos.CharityDtoResponse();
          }
          CharityRes.MergeFrom(other.CharityRes);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::teledon_management_ui.Protos.AuthUserRequest subBuilder = new global::teledon_management_ui.Protos.AuthUserRequest();
            if (payloadCase_ == PayloadOneofCase.AuthReq) {
              subBuilder.MergeFrom(AuthReq);
            }
            input.ReadMessage(subBuilder);
            AuthReq = subBuilder;
            break;
          }
          case 18: {
            global::teledon_management_ui.Protos.AuthUserResponse subBuilder = new global::teledon_management_ui.Protos.AuthUserResponse();
            if (payloadCase_ == PayloadOneofCase.AuthRes) {
              subBuilder.MergeFrom(AuthRes);
            }
            input.ReadMessage(subBuilder);
            AuthRes = subBuilder;
            break;
          }
          case 26: {
            global::teledon_management_ui.Protos.CharityDtoRequest subBuilder = new global::teledon_management_ui.Protos.CharityDtoRequest();
            if (payloadCase_ == PayloadOneofCase.CharityReq) {
              subBuilder.MergeFrom(CharityReq);
            }
            input.ReadMessage(subBuilder);
            CharityReq = subBuilder;
            break;
          }
          case 34: {
            global::teledon_management_ui.Protos.CharityDtoResponse subBuilder = new global::teledon_management_ui.Protos.CharityDtoResponse();
            if (payloadCase_ == PayloadOneofCase.CharityRes) {
              subBuilder.MergeFrom(CharityRes);
            }
            input.ReadMessage(subBuilder);
            CharityRes = subBuilder;
            break;
          }
          case 40: {
            IsUpdatePayload = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::teledon_management_ui.Protos.AuthUserRequest subBuilder = new global::teledon_management_ui.Protos.AuthUserRequest();
            if (payloadCase_ == PayloadOneofCase.AuthReq) {
              subBuilder.MergeFrom(AuthReq);
            }
            input.ReadMessage(subBuilder);
            AuthReq = subBuilder;
            break;
          }
          case 18: {
            global::teledon_management_ui.Protos.AuthUserResponse subBuilder = new global::teledon_management_ui.Protos.AuthUserResponse();
            if (payloadCase_ == PayloadOneofCase.AuthRes) {
              subBuilder.MergeFrom(AuthRes);
            }
            input.ReadMessage(subBuilder);
            AuthRes = subBuilder;
            break;
          }
          case 26: {
            global::teledon_management_ui.Protos.CharityDtoRequest subBuilder = new global::teledon_management_ui.Protos.CharityDtoRequest();
            if (payloadCase_ == PayloadOneofCase.CharityReq) {
              subBuilder.MergeFrom(CharityReq);
            }
            input.ReadMessage(subBuilder);
            CharityReq = subBuilder;
            break;
          }
          case 34: {
            global::teledon_management_ui.Protos.CharityDtoResponse subBuilder = new global::teledon_management_ui.Protos.CharityDtoResponse();
            if (payloadCase_ == PayloadOneofCase.CharityRes) {
              subBuilder.MergeFrom(CharityRes);
            }
            input.ReadMessage(subBuilder);
            CharityRes = subBuilder;
            break;
          }
          case 40: {
            IsUpdatePayload = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
