// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: main_message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace teledon_management_ui.Protos {

  /// <summary>Holder for reflection information generated from main_message.proto</summary>
  public static partial class MainMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for main_message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MainMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJtYWluX21lc3NhZ2UucHJvdG8SEnRlbGVkb25fbWFuYWdlbWVudBoNY2hh",
            "cml0eS5wcm90bxoPYXV0aF91c2VyLnByb3RvGgtkb25vci5wcm90bxoOZG9u",
            "YXRpb24ucHJvdG8iogQKC01haW5NZXNzYWdlEhwKD2lzVXBkYXRlUGF5bG9h",
            "ZBgBIAEoCEgBiAEBEjYKB2F1dGhSZXEYAiABKAsyIy50ZWxlZG9uX21hbmFn",
            "ZW1lbnQuQXV0aFVzZXJSZXF1ZXN0SAASNwoHYXV0aFJlcxgDIAEoCzIkLnRl",
            "bGVkb25fbWFuYWdlbWVudC5BdXRoVXNlclJlc3BvbnNlSAASOwoKY2hhcml0",
            "eVJlcRgEIAEoCzIlLnRlbGVkb25fbWFuYWdlbWVudC5DaGFyaXR5RHRvUmVx",
            "dWVzdEgAEjwKCmNoYXJpdHlSZXMYBSABKAsyJi50ZWxlZG9uX21hbmFnZW1l",
            "bnQuQ2hhcml0eUR0b1Jlc3BvbnNlSAASNwoIZG9ub3JSZXEYBiABKAsyIy50",
            "ZWxlZG9uX21hbmFnZW1lbnQuRG9ub3JEdG9SZXF1ZXN0SAASOAoIZG9ub3JS",
            "ZXMYByABKAsyJC50ZWxlZG9uX21hbmFnZW1lbnQuRG9ub3JEdG9SZXNwb25z",
            "ZUgAEjoKC2RvbmF0aW9uUmVxGAggASgLMiMudGVsZWRvbl9tYW5hZ2VtZW50",
            "LkRvbmF0aW9uUmVxdWVzdEgAEjsKC2RvbmF0aW9uUmVzGAkgASgLMiQudGVs",
            "ZWRvbl9tYW5hZ2VtZW50LkRvbmF0aW9uUmVzcG9uc2VIAEIJCgdwYXlsb2Fk",
            "QhIKEF9pc1VwZGF0ZVBheWxvYWRCUQobbWUuYWxleHV0enp1LnRlbGVkb24u",
            "cHJvdG9zQhFNYWluTWVzc2FnZVByb3Rvc1AAqgIcdGVsZWRvbl9tYW5hZ2Vt",
            "ZW50X3VpLlByb3Rvc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::teledon_management_ui.Protos.CharityReflection.Descriptor, global::teledon_management_ui.Protos.AuthUserReflection.Descriptor, global::teledon_management_ui.Protos.DonorReflection.Descriptor, global::teledon_management_ui.Protos.DonationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::teledon_management_ui.Protos.MainMessage), global::teledon_management_ui.Protos.MainMessage.Parser, new[]{ "IsUpdatePayload", "AuthReq", "AuthRes", "CharityReq", "CharityRes", "DonorReq", "DonorRes", "DonationReq", "DonationRes" }, new[]{ "Payload", "IsUpdatePayload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MainMessage : pb::IMessage<MainMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MainMessage> _parser = new pb::MessageParser<MainMessage>(() => new MainMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MainMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::teledon_management_ui.Protos.MainMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainMessage(MainMessage other) : this() {
      _hasBits0 = other._hasBits0;
      isUpdatePayload_ = other.isUpdatePayload_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.AuthReq:
          AuthReq = other.AuthReq.Clone();
          break;
        case PayloadOneofCase.AuthRes:
          AuthRes = other.AuthRes.Clone();
          break;
        case PayloadOneofCase.CharityReq:
          CharityReq = other.CharityReq.Clone();
          break;
        case PayloadOneofCase.CharityRes:
          CharityRes = other.CharityRes.Clone();
          break;
        case PayloadOneofCase.DonorReq:
          DonorReq = other.DonorReq.Clone();
          break;
        case PayloadOneofCase.DonorRes:
          DonorRes = other.DonorRes.Clone();
          break;
        case PayloadOneofCase.DonationReq:
          DonationReq = other.DonationReq.Clone();
          break;
        case PayloadOneofCase.DonationRes:
          DonationRes = other.DonationRes.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainMessage Clone() {
      return new MainMessage(this);
    }

    /// <summary>Field number for the "isUpdatePayload" field.</summary>
    public const int IsUpdatePayloadFieldNumber = 1;
    private readonly static bool IsUpdatePayloadDefaultValue = false;

    private bool isUpdatePayload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsUpdatePayload {
      get { if ((_hasBits0 & 1) != 0) { return isUpdatePayload_; } else { return IsUpdatePayloadDefaultValue; } }
      set {
        _hasBits0 |= 1;
        isUpdatePayload_ = value;
      }
    }
    /// <summary>Gets whether the "isUpdatePayload" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIsUpdatePayload {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "isUpdatePayload" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIsUpdatePayload() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "authReq" field.</summary>
    public const int AuthReqFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.AuthUserRequest AuthReq {
      get { return payloadCase_ == PayloadOneofCase.AuthReq ? (global::teledon_management_ui.Protos.AuthUserRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.AuthReq;
      }
    }

    /// <summary>Field number for the "authRes" field.</summary>
    public const int AuthResFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.AuthUserResponse AuthRes {
      get { return payloadCase_ == PayloadOneofCase.AuthRes ? (global::teledon_management_ui.Protos.AuthUserResponse) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.AuthRes;
      }
    }

    /// <summary>Field number for the "charityReq" field.</summary>
    public const int CharityReqFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.CharityDtoRequest CharityReq {
      get { return payloadCase_ == PayloadOneofCase.CharityReq ? (global::teledon_management_ui.Protos.CharityDtoRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CharityReq;
      }
    }

    /// <summary>Field number for the "charityRes" field.</summary>
    public const int CharityResFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.CharityDtoResponse CharityRes {
      get { return payloadCase_ == PayloadOneofCase.CharityRes ? (global::teledon_management_ui.Protos.CharityDtoResponse) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.CharityRes;
      }
    }

    /// <summary>Field number for the "donorReq" field.</summary>
    public const int DonorReqFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.DonorDtoRequest DonorReq {
      get { return payloadCase_ == PayloadOneofCase.DonorReq ? (global::teledon_management_ui.Protos.DonorDtoRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.DonorReq;
      }
    }

    /// <summary>Field number for the "donorRes" field.</summary>
    public const int DonorResFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.DonorDtoResponse DonorRes {
      get { return payloadCase_ == PayloadOneofCase.DonorRes ? (global::teledon_management_ui.Protos.DonorDtoResponse) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.DonorRes;
      }
    }

    /// <summary>Field number for the "donationReq" field.</summary>
    public const int DonationReqFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.DonationRequest DonationReq {
      get { return payloadCase_ == PayloadOneofCase.DonationReq ? (global::teledon_management_ui.Protos.DonationRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.DonationReq;
      }
    }

    /// <summary>Field number for the "donationRes" field.</summary>
    public const int DonationResFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::teledon_management_ui.Protos.DonationResponse DonationRes {
      get { return payloadCase_ == PayloadOneofCase.DonationRes ? (global::teledon_management_ui.Protos.DonationResponse) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.DonationRes;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      AuthReq = 2,
      AuthRes = 3,
      CharityReq = 4,
      CharityRes = 5,
      DonorReq = 6,
      DonorRes = 7,
      DonationReq = 8,
      DonationRes = 9,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MainMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MainMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsUpdatePayload != other.IsUpdatePayload) return false;
      if (!object.Equals(AuthReq, other.AuthReq)) return false;
      if (!object.Equals(AuthRes, other.AuthRes)) return false;
      if (!object.Equals(CharityReq, other.CharityReq)) return false;
      if (!object.Equals(CharityRes, other.CharityRes)) return false;
      if (!object.Equals(DonorReq, other.DonorReq)) return false;
      if (!object.Equals(DonorRes, other.DonorRes)) return false;
      if (!object.Equals(DonationReq, other.DonationReq)) return false;
      if (!object.Equals(DonationRes, other.DonationRes)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasIsUpdatePayload) hash ^= IsUpdatePayload.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.AuthReq) hash ^= AuthReq.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.AuthRes) hash ^= AuthRes.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CharityReq) hash ^= CharityReq.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.CharityRes) hash ^= CharityRes.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.DonorReq) hash ^= DonorReq.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.DonorRes) hash ^= DonorRes.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.DonationReq) hash ^= DonationReq.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.DonationRes) hash ^= DonationRes.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasIsUpdatePayload) {
        output.WriteRawTag(8);
        output.WriteBool(IsUpdatePayload);
      }
      if (payloadCase_ == PayloadOneofCase.AuthReq) {
        output.WriteRawTag(18);
        output.WriteMessage(AuthReq);
      }
      if (payloadCase_ == PayloadOneofCase.AuthRes) {
        output.WriteRawTag(26);
        output.WriteMessage(AuthRes);
      }
      if (payloadCase_ == PayloadOneofCase.CharityReq) {
        output.WriteRawTag(34);
        output.WriteMessage(CharityReq);
      }
      if (payloadCase_ == PayloadOneofCase.CharityRes) {
        output.WriteRawTag(42);
        output.WriteMessage(CharityRes);
      }
      if (payloadCase_ == PayloadOneofCase.DonorReq) {
        output.WriteRawTag(50);
        output.WriteMessage(DonorReq);
      }
      if (payloadCase_ == PayloadOneofCase.DonorRes) {
        output.WriteRawTag(58);
        output.WriteMessage(DonorRes);
      }
      if (payloadCase_ == PayloadOneofCase.DonationReq) {
        output.WriteRawTag(66);
        output.WriteMessage(DonationReq);
      }
      if (payloadCase_ == PayloadOneofCase.DonationRes) {
        output.WriteRawTag(74);
        output.WriteMessage(DonationRes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasIsUpdatePayload) {
        output.WriteRawTag(8);
        output.WriteBool(IsUpdatePayload);
      }
      if (payloadCase_ == PayloadOneofCase.AuthReq) {
        output.WriteRawTag(18);
        output.WriteMessage(AuthReq);
      }
      if (payloadCase_ == PayloadOneofCase.AuthRes) {
        output.WriteRawTag(26);
        output.WriteMessage(AuthRes);
      }
      if (payloadCase_ == PayloadOneofCase.CharityReq) {
        output.WriteRawTag(34);
        output.WriteMessage(CharityReq);
      }
      if (payloadCase_ == PayloadOneofCase.CharityRes) {
        output.WriteRawTag(42);
        output.WriteMessage(CharityRes);
      }
      if (payloadCase_ == PayloadOneofCase.DonorReq) {
        output.WriteRawTag(50);
        output.WriteMessage(DonorReq);
      }
      if (payloadCase_ == PayloadOneofCase.DonorRes) {
        output.WriteRawTag(58);
        output.WriteMessage(DonorRes);
      }
      if (payloadCase_ == PayloadOneofCase.DonationReq) {
        output.WriteRawTag(66);
        output.WriteMessage(DonationReq);
      }
      if (payloadCase_ == PayloadOneofCase.DonationRes) {
        output.WriteRawTag(74);
        output.WriteMessage(DonationRes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasIsUpdatePayload) {
        size += 1 + 1;
      }
      if (payloadCase_ == PayloadOneofCase.AuthReq) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AuthReq);
      }
      if (payloadCase_ == PayloadOneofCase.AuthRes) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AuthRes);
      }
      if (payloadCase_ == PayloadOneofCase.CharityReq) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CharityReq);
      }
      if (payloadCase_ == PayloadOneofCase.CharityRes) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CharityRes);
      }
      if (payloadCase_ == PayloadOneofCase.DonorReq) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DonorReq);
      }
      if (payloadCase_ == PayloadOneofCase.DonorRes) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DonorRes);
      }
      if (payloadCase_ == PayloadOneofCase.DonationReq) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DonationReq);
      }
      if (payloadCase_ == PayloadOneofCase.DonationRes) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DonationRes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MainMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasIsUpdatePayload) {
        IsUpdatePayload = other.IsUpdatePayload;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.AuthReq:
          if (AuthReq == null) {
            AuthReq = new global::teledon_management_ui.Protos.AuthUserRequest();
          }
          AuthReq.MergeFrom(other.AuthReq);
          break;
        case PayloadOneofCase.AuthRes:
          if (AuthRes == null) {
            AuthRes = new global::teledon_management_ui.Protos.AuthUserResponse();
          }
          AuthRes.MergeFrom(other.AuthRes);
          break;
        case PayloadOneofCase.CharityReq:
          if (CharityReq == null) {
            CharityReq = new global::teledon_management_ui.Protos.CharityDtoRequest();
          }
          CharityReq.MergeFrom(other.CharityReq);
          break;
        case PayloadOneofCase.CharityRes:
          if (CharityRes == null) {
            CharityRes = new global::teledon_management_ui.Protos.CharityDtoResponse();
          }
          CharityRes.MergeFrom(other.CharityRes);
          break;
        case PayloadOneofCase.DonorReq:
          if (DonorReq == null) {
            DonorReq = new global::teledon_management_ui.Protos.DonorDtoRequest();
          }
          DonorReq.MergeFrom(other.DonorReq);
          break;
        case PayloadOneofCase.DonorRes:
          if (DonorRes == null) {
            DonorRes = new global::teledon_management_ui.Protos.DonorDtoResponse();
          }
          DonorRes.MergeFrom(other.DonorRes);
          break;
        case PayloadOneofCase.DonationReq:
          if (DonationReq == null) {
            DonationReq = new global::teledon_management_ui.Protos.DonationRequest();
          }
          DonationReq.MergeFrom(other.DonationReq);
          break;
        case PayloadOneofCase.DonationRes:
          if (DonationRes == null) {
            DonationRes = new global::teledon_management_ui.Protos.DonationResponse();
          }
          DonationRes.MergeFrom(other.DonationRes);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsUpdatePayload = input.ReadBool();
            break;
          }
          case 18: {
            global::teledon_management_ui.Protos.AuthUserRequest subBuilder = new global::teledon_management_ui.Protos.AuthUserRequest();
            if (payloadCase_ == PayloadOneofCase.AuthReq) {
              subBuilder.MergeFrom(AuthReq);
            }
            input.ReadMessage(subBuilder);
            AuthReq = subBuilder;
            break;
          }
          case 26: {
            global::teledon_management_ui.Protos.AuthUserResponse subBuilder = new global::teledon_management_ui.Protos.AuthUserResponse();
            if (payloadCase_ == PayloadOneofCase.AuthRes) {
              subBuilder.MergeFrom(AuthRes);
            }
            input.ReadMessage(subBuilder);
            AuthRes = subBuilder;
            break;
          }
          case 34: {
            global::teledon_management_ui.Protos.CharityDtoRequest subBuilder = new global::teledon_management_ui.Protos.CharityDtoRequest();
            if (payloadCase_ == PayloadOneofCase.CharityReq) {
              subBuilder.MergeFrom(CharityReq);
            }
            input.ReadMessage(subBuilder);
            CharityReq = subBuilder;
            break;
          }
          case 42: {
            global::teledon_management_ui.Protos.CharityDtoResponse subBuilder = new global::teledon_management_ui.Protos.CharityDtoResponse();
            if (payloadCase_ == PayloadOneofCase.CharityRes) {
              subBuilder.MergeFrom(CharityRes);
            }
            input.ReadMessage(subBuilder);
            CharityRes = subBuilder;
            break;
          }
          case 50: {
            global::teledon_management_ui.Protos.DonorDtoRequest subBuilder = new global::teledon_management_ui.Protos.DonorDtoRequest();
            if (payloadCase_ == PayloadOneofCase.DonorReq) {
              subBuilder.MergeFrom(DonorReq);
            }
            input.ReadMessage(subBuilder);
            DonorReq = subBuilder;
            break;
          }
          case 58: {
            global::teledon_management_ui.Protos.DonorDtoResponse subBuilder = new global::teledon_management_ui.Protos.DonorDtoResponse();
            if (payloadCase_ == PayloadOneofCase.DonorRes) {
              subBuilder.MergeFrom(DonorRes);
            }
            input.ReadMessage(subBuilder);
            DonorRes = subBuilder;
            break;
          }
          case 66: {
            global::teledon_management_ui.Protos.DonationRequest subBuilder = new global::teledon_management_ui.Protos.DonationRequest();
            if (payloadCase_ == PayloadOneofCase.DonationReq) {
              subBuilder.MergeFrom(DonationReq);
            }
            input.ReadMessage(subBuilder);
            DonationReq = subBuilder;
            break;
          }
          case 74: {
            global::teledon_management_ui.Protos.DonationResponse subBuilder = new global::teledon_management_ui.Protos.DonationResponse();
            if (payloadCase_ == PayloadOneofCase.DonationRes) {
              subBuilder.MergeFrom(DonationRes);
            }
            input.ReadMessage(subBuilder);
            DonationRes = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsUpdatePayload = input.ReadBool();
            break;
          }
          case 18: {
            global::teledon_management_ui.Protos.AuthUserRequest subBuilder = new global::teledon_management_ui.Protos.AuthUserRequest();
            if (payloadCase_ == PayloadOneofCase.AuthReq) {
              subBuilder.MergeFrom(AuthReq);
            }
            input.ReadMessage(subBuilder);
            AuthReq = subBuilder;
            break;
          }
          case 26: {
            global::teledon_management_ui.Protos.AuthUserResponse subBuilder = new global::teledon_management_ui.Protos.AuthUserResponse();
            if (payloadCase_ == PayloadOneofCase.AuthRes) {
              subBuilder.MergeFrom(AuthRes);
            }
            input.ReadMessage(subBuilder);
            AuthRes = subBuilder;
            break;
          }
          case 34: {
            global::teledon_management_ui.Protos.CharityDtoRequest subBuilder = new global::teledon_management_ui.Protos.CharityDtoRequest();
            if (payloadCase_ == PayloadOneofCase.CharityReq) {
              subBuilder.MergeFrom(CharityReq);
            }
            input.ReadMessage(subBuilder);
            CharityReq = subBuilder;
            break;
          }
          case 42: {
            global::teledon_management_ui.Protos.CharityDtoResponse subBuilder = new global::teledon_management_ui.Protos.CharityDtoResponse();
            if (payloadCase_ == PayloadOneofCase.CharityRes) {
              subBuilder.MergeFrom(CharityRes);
            }
            input.ReadMessage(subBuilder);
            CharityRes = subBuilder;
            break;
          }
          case 50: {
            global::teledon_management_ui.Protos.DonorDtoRequest subBuilder = new global::teledon_management_ui.Protos.DonorDtoRequest();
            if (payloadCase_ == PayloadOneofCase.DonorReq) {
              subBuilder.MergeFrom(DonorReq);
            }
            input.ReadMessage(subBuilder);
            DonorReq = subBuilder;
            break;
          }
          case 58: {
            global::teledon_management_ui.Protos.DonorDtoResponse subBuilder = new global::teledon_management_ui.Protos.DonorDtoResponse();
            if (payloadCase_ == PayloadOneofCase.DonorRes) {
              subBuilder.MergeFrom(DonorRes);
            }
            input.ReadMessage(subBuilder);
            DonorRes = subBuilder;
            break;
          }
          case 66: {
            global::teledon_management_ui.Protos.DonationRequest subBuilder = new global::teledon_management_ui.Protos.DonationRequest();
            if (payloadCase_ == PayloadOneofCase.DonationReq) {
              subBuilder.MergeFrom(DonationReq);
            }
            input.ReadMessage(subBuilder);
            DonationReq = subBuilder;
            break;
          }
          case 74: {
            global::teledon_management_ui.Protos.DonationResponse subBuilder = new global::teledon_management_ui.Protos.DonationResponse();
            if (payloadCase_ == PayloadOneofCase.DonationRes) {
              subBuilder.MergeFrom(DonationRes);
            }
            input.ReadMessage(subBuilder);
            DonationRes = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
