// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: response_status.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace teledon_management_ui.Protos {

  /// <summary>Holder for reflection information generated from response_status.proto</summary>
  public static partial class ResponseStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for response_status.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponseStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVyZXNwb25zZV9zdGF0dXMucHJvdG8SEnRlbGVkb25fbWFuYWdlbWVudCok",
            "Cg5SZXNwb25zZVN0YXR1cxIGCgJPSxAAEgoKBkZBSUxFRBABQlQKG21lLmFs",
            "ZXh1dHp6dS50ZWxlZG9uLnByb3Rvc0IUUmVzcG9uc2VTdGF0dXNQcm90b3NQ",
            "AKoCHHRlbGVkb25fbWFuYWdlbWVudF91aS5Qcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::teledon_management_ui.Protos.ResponseStatus), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ResponseStatus {
    [pbr::OriginalName("OK")] Ok = 0,
    [pbr::OriginalName("FAILED")] Failed = 1,
  }

  #endregion

}

#endregion Designer generated code
